#!/usr/bin/env ruby
#
# If you need a compiled version of the CSS from dvl-core, this script
# can generate it for you.
#
# Usage:
#
#   ./script/compile app
#   ./script/compile core
#   ./script/compile components/dropdown
#
# The compiled CSS will be written to the `dist` directory, which is
# .gitignore'd for your convenience.

require File.expand_path("../../spec/dummy/config/environment.rb",  __FILE__)
require 'sass'

stylesheets = [
  'core',
  'app'
]

Array(ARGV).each do |x|
  asset = Rails.application.assets.find_asset("dvl/#{x}.scss")

  compiled = ::Sass::Engine.new(
    asset.body,
    syntax: :scss,
    cache: false,
    read_cache: false,
    style: :nested
  ).render

  Dir.mkdir('dist') rescue Errno::EEXIST
  File.write "dist/#{x.gsub('/', '-')}.css", compiled
end
