#!/bin/sh
# Tag and push a release.

set -e

git checkout -b tmp-deploy
sed -i '' "/Gemfile.lock/d" .gitignore
bundle install
git add .
git commit -am 'Deploy to Heroku'
git push heroku tmp-deploy:master --force
git checkout master
git branch -D tmp-deploy
